spring.application.name=QuanLyKhachSan
spring.datasource.url=jdbc:postgresql://localhost:5432/quanlykhachsan
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# câu hình sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
