spring.application.name=QuanLyKhachSan
server.port=9999
spring.datasource.url=jdbc:postgresql://localhost:5432/quanlykhachsan2
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# câu hình sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# c?u hình cloady
cloud-name=dqsn1crl0
api-key=527729112526488
api-secret=_slsMpvamydmKOA_Mol3CBUYJK8


# jwt
jwt.secret-key=haomilosinhraoninhbinhqualamotdieuthuyetvoiw
jwt.expired=900000



#ko bi?t n?a th?y chat b?o v?y
spring.jpa.open-in-view=false