spring.application.name=QuanLyKhachSan

spring.datasource.url=jdbc:postgresql://localhost:5432/quanlykhachsan3
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# c?u h?nh sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# c?u h?nh cloady
cloud-name=dqsn1crl0
api-key=527729112526488
api-secret=_slsMpvamydmKOA_Mol3CBUYJK8
# Gi?i h?n dung l??ng t?i ?a cho 1 file single upload
spring.servlet.multipart.max-file-size=10MB

# Gi?i h?n dung l??ng t?i ?a cho to?n b? request (g?m nhi?u file n?u c?)
spring.servlet.multipart.max-request-size=50MB

# jwt
jwt.secret-key=haomilosinhraoninhbinhqualamotdieuthuyetvoiw
jwt.expired=900000



#ko bi?t n?a th?y chat b?o v?y
spring.jpa.open-in-view=false


#c?u h?nh mail
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:haovu1663@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# mk app ogvcpqvqftjxtapk

brevo.api-key=${BREVO_API_KEY:}
brevo.sender-email=${BREVO_SENDER_EMAIL:haovu1663@gmail.com}
brevo.sender-name=Khach San